using ONIONARCH.Application.Abstractions;
using ONIONARCH.Application.Abstractions.Context;
using ONIONARCH.Domain.Entities;

namespace ONIONARCH.Application.Actions.SampleEntityEFCore.Commands;

/// <summary>
/// Command to insert many sample entities in one bulk operation through the EF Core bulk port.
/// </summary>
/// <param name="SampleEntities">The entities to insert. Their keys are generated by the database.</param>
public sealed record BulkCreateSampleEntityEFCoreRequest(IReadOnlyCollection<SampleEntityDefinition> SampleEntities)
    : ICommandRequest<Result<IReadOnlyList<int>>>;

/// <summary>
/// Handles <see cref="BulkCreateSampleEntityEFCoreRequest"/> using the EF Core bulk command port.
/// </summary>
/// <param name="bulkCommandDbContext">The write-side EF Core bulk port.</param>
internal sealed class BulkCreateSampleEntityEFCoreHandler(IBulkCommandDbContext bulkCommandDbContext)
    : ICommandHandler<BulkCreateSampleEntityEFCoreRequest, Result<IReadOnlyList<int>>>
{
    /// <summary>
    /// Bulk inserts the requested entities and reads the database-generated keys back into them.
    /// </summary>
    /// <param name="request">The command carrying the entities to insert.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>
    /// A successful result containing the generated keys in the order the entities were supplied, or a
    /// validation failure if the request carries no entities.
    /// </returns>
    /// <exception cref="NotSupportedException">The command database platform does not support bulk inserts.</exception>
    public async Task<Result<IReadOnlyList<int>>> Handle(
        BulkCreateSampleEntityEFCoreRequest request,
        CancellationToken cancellationToken)
    {
        if (request.SampleEntities is not { Count: > 0 })
        {
            return Result<IReadOnlyList<int>>.Failure("At least one sample entity is required.", ResultErrorType.Validation);
        }

        await bulkCommandDbContext.BulkInsertAsync(request.SampleEntities, retrieveGeneratedKeys: true, cancellationToken);
        return Result<IReadOnlyList<int>>.Success([.. request.SampleEntities.Select(e => e.SampleId)]);
    }
}
